version: "3.9"

services:
  app3:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - gunicorn
      - main_page.wsgi:application
      - --bind
      - "0.0.0.0:8002"
    ports:
      - "8002:8002"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200K"
    volumes:
      - ./main_page/database:/app3/database